--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 02.09.2019 23:22:00
-- Server version: 8.0.17
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE restaurant;

--
-- Drop table `rorder_position`
--
DROP TABLE IF EXISTS rorder_position;

--
-- Drop table `rorders`
--
DROP TABLE IF EXISTS rorders;

--
-- Drop table `susers`
--
DROP TABLE IF EXISTS susers;

--
-- Drop table `sitems`
--
DROP TABLE IF EXISTS sitems;

--
-- Drop table `scategory`
--
DROP TABLE IF EXISTS scategory;

--
-- Set default database
--
USE restaurant;

--
-- Create table `scategory`
--
CREATE TABLE scategory (
  category_id INT(11) NOT NULL,
  parent_id INT(11) DEFAULT NULL,
  name VARCHAR(255) DEFAULT NULL,
  description VARCHAR(255) DEFAULT NULL,
  active TINYINT(4) NOT NULL DEFAULT 1,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (category_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Справочник категорий блюд';

--
-- Create table `sitems`
--
CREATE TABLE sitems (
  item_id INT(11) NOT NULL AUTO_INCREMENT,
  category_id INT(11) DEFAULT NULL,
  name VARCHAR(255) DEFAULT NULL,
  description VARCHAR(255) DEFAULT NULL,
  coast DECIMAL(10, 2) DEFAULT NULL,
  image VARCHAR(255) DEFAULT NULL,
  active TINYINT(4) NOT NULL DEFAULT 1,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (item_id),
  UNIQUE INDEX UK_sitems_item_id(item_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Справочник блюд';

--
-- Create foreign key
--
ALTER TABLE sitems 
  ADD CONSTRAINT FK_sitems_category_id FOREIGN KEY (category_id)
    REFERENCES scategory(category_id);

--
-- Create table `susers`
--
CREATE TABLE susers (
  user_id INT(11) NOT NULL AUTO_INCREMENT,
  active TINYINT(4) DEFAULT 1,
  fullname VARCHAR(255) DEFAULT NULL,
  login VARCHAR(255) DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  is_admin TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id),
  UNIQUE INDEX UK_susers_user_id(user_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Справочник пользователей';

--
-- Create table `rorders`
--
CREATE TABLE rorders (
  order_id INT(11) NOT NULL AUTO_INCREMENT,
  user_id INT(11) NOT NULL,
  order_number INT(11) DEFAULT NULL,
  active TINYINT(4) NOT NULL DEFAULT 1,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (order_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Реестр заказов';

--
-- Create foreign key
--
ALTER TABLE rorders 
  ADD CONSTRAINT FK_rorders_user_id FOREIGN KEY (user_id)
    REFERENCES susers(user_id);

--
-- Create table `rorder_position`
--
CREATE TABLE rorder_position (
  position_id INT(11) NOT NULL,
  order_id INT(11) NOT NULL,
  item_id INT(11) NOT NULL,
  coast DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  active TINYINT(4) NOT NULL DEFAULT 1,
  update_time DATETIME DEFAULT NULL,
  PRIMARY KEY (position_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Реестр заказов блюд';

--
-- Create foreign key
--
ALTER TABLE rorder_position 
  ADD CONSTRAINT FK_rcheck_position_item_id FOREIGN KEY (item_id)
    REFERENCES sitems(item_id);

--
-- Create foreign key
--
ALTER TABLE rorder_position 
  ADD CONSTRAINT FK_rcheck_position_order_id FOREIGN KEY (order_id)
    REFERENCES rorders(order_id);

-- 
-- Dumping data for table scategory
--
-- Table restaurant.scategory does not contain any data (it is empty)

-- 
-- Dumping data for table susers
--
INSERT INTO susers VALUES
(1, 1, 'Alex', 'atmka', '111', '2019-09-01 00:00:00', 0),
(18, 1, 'Tom Tompkins', 'login1', '111', '2019-09-02 18:54:35', 0),
(19, 0, 'Tom Holland', 'login2', '111', '2019-09-02 18:54:37', 0),
(20, 1, 'Васька Петров', 'login3', '111', '2019-09-02 18:54:37', 0),
(21, 0, 'Антон Шевчук', 'login4', '111', '2019-09-02 18:54:37', 1),
(22, 0, 'Алексей Биянов', 'login5', '111', '2019-09-02 18:54:37', 1),
(23, 1, 'Какой-то чел', 'login6', '111', '2019-09-02 18:54:37', 0),
(25, 1, 'Tom Tompkins', 'login1', '111', '2019-09-02 18:55:16', 0),
(26, 0, 'Tom Holland', 'login2', '111', '2019-09-02 18:55:17', 0),
(27, 1, 'Васька Петров', 'login3', '111', '2019-09-02 18:55:17', 0),
(28, 0, 'Антон Шевчук', 'login4', '111', '2019-09-02 18:55:17', 1),
(29, 0, 'Алексей Биянов', 'login5', '111', '2019-09-02 18:55:17', 1),
(30, 1, 'Какой-то чел', 'login6', '111', '2019-09-02 18:55:17', 0),
(31, 0, 'Ещё один непонятный', 'login7', '111', '2019-09-02 18:55:17', 0),
(32, 1, 'Tom Tompkins', 'login1', '111', '2019-09-02 19:11:04', 0),
(33, 0, 'Tom Holland', 'login2', '111', '2019-09-02 19:11:05', 0),
(34, 1, 'Васька Петров', 'login3', '111', '2019-09-02 19:11:05', 0),
(35, 0, 'Антон Шевчук', 'login4', '111', '2019-09-02 19:11:05', 1),
(36, 0, 'Алексей Биянов', 'login5', '111', '2019-09-02 19:11:05', 1),
(37, 1, 'Какой-то чел', 'login6', '111', '2019-09-02 19:11:05', 0),
(38, 0, 'Ещё один непонятный', 'login7', '111', '2019-09-02 19:11:05', 0),
(39, 1, 'Tom Tompkins', 'login1', '111', '2019-09-02 19:15:54', 0),
(40, 0, 'Tom Holland', 'login2', '111', '2019-09-02 19:15:55', 0),
(41, 1, 'Васька Петров', 'login3', '111', '2019-09-02 19:15:55', 0),
(42, 0, 'Антон Шевчук', 'login4', '111', '2019-09-02 19:15:55', 1),
(43, 0, 'Алексей Биянов', 'login5', '111', '2019-09-02 19:15:55', 1),
(44, 1, 'Какой-то чел', 'login6', '111', '2019-09-02 19:15:55', 0),
(45, 0, 'Ещё один непонятный', 'login7', '111', '2019-09-02 19:15:55', 0);

-- 
-- Dumping data for table sitems
--
-- Table restaurant.sitems does not contain any data (it is empty)

-- 
-- Dumping data for table rorders
--
-- Table restaurant.rorders does not contain any data (it is empty)

-- 
-- Dumping data for table rorder_position
--
-- Table restaurant.rorder_position does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;